apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codegen-mar14-host-1-app
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/codegen-mar14-host-1/overlays/development
    repoURL: https://github.com/redhat-appstudio-mjf/codegen-mar14-host-1-gitops.git
    targetRevision: main
  destination:
    server: https://api.mfaisal-mar14.devcluster.openshift.com:6443
    namespace: codegen-mar14-1
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: ai-rhdh
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
