apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: codegen-mar14-host-1
  janus-idp.io/tekton: codegen-mar14-host-1
  backstage.io/kubernetes-id: codegen-mar14-host-1
  backstage.io/kubernetes-namespace: codegen-mar14-1
  app.kubernetes.io/part-of: codegen-mar14-host-1
resources:
- application-dev.yaml
- application-tekton.yaml